Rely on git’s gpg.minTrustLevel flag
QubesOS/qubes-builder pull request #145
Opened 2020-11-30 04:48 UTC by DemiMarie

Git supports setting the minimum GPG trust level, which in our case
should be “fully”.  This avoids having to parse the output of GPG
ourselves, and allows us to rely on the parser built-in to Git.

2020-12-01 05:56 UTC, marmarek requested changes
Generally I like the change, but there is one issue: this option is available in git >= 2.26.0, which was released just half a year ago and for example Debian stable doesn't have it.
Since git silently ignore unknown options, running this on too old git may result in accepting signatures that shouldn't be accepted.

I'm not sure what's the best way to detect if this is supported, but if nothing else, then a version check on git is necessary. And in case of too old git, fallback to the old code. Once major distributions (like Debian stable) will have git new enough, we can change the fallback to an error.

2020-12-01 15:51 UTC, DemiMarie commented
Would a feature request for a `--min-trust-level` flag be a good idea?

2020-12-01 16:28 UTC, marmarek commented
In general, specifying this in config is a better idea for the future - harder to forget it in direct (non-scripted) use. Just the transitional period is messy because of ignoring unknown options. Maybe there is a way to list supported options?.

2020-12-01 16:37 UTC, DemiMarie commented
None that I can think of (other than `man 1 git-config`, but that’s silly :laughing:).

I personally *do* specify it in `~/.config/git/config`, along with `merge.verifySignatures=1`, but we can’t rely on that in qubes-builder.  That’s also why I included `merge.verifySignatures=false`.

I would be fine with a version check, although at this point the script is starting to look like Perl :smile:.

2020-12-03 15:40 UTC, DemiMarie commented
Now that #146 has been merged, we use *both* `gpg.minTrustLevel` and manual parsing of GPG’s output.  Both must pass for a signature to be accepted.

2020-12-03 15:40 UTC, closed without merging